[package]
name = "tetengo_trie"
version = "1.1.0"
authors = ["kaoru"]
edition = "2021"
description = "A trie library implemented with a double array"
readme = "README.md"
homepage = "https://www.tetengo.org/"
repository = "https://github.com/tetengo/tetengo.rs"
license = "MIT"
keywords = [
    "common-prefix-search",
    "data-structure",
    "double-array",
    "search",
    "trie",
]
categories = [
    "algorithms",
    "data-structures",
    "text-processing",
]

[dependencies]
anyhow = "1.0.83"
hashlink = "0.8.4"
memmap2 = "0.7.1"
once_cell = "1.19.0"
tempfile = "3.10.1"
thiserror = "1.0.60"
