[package]
name = "tetengo_trie"
version = "0.1.3"
authors = ["kaoru"]
edition = "2021"
description = "A trie library implemented double arrays"
readme = "README.md"
homepage = "https://www.tetengo.org/"
repository = "https://github.com/tetengo/tetengo.rs"
license = "MIT"
keywords = ["trie", "double_array", "common_prefix_search", "assoc_container"]
categories = ["algorithms", "text-processing"]

[dependencies]
anyhow = "1.0.71"
memmap2 = "0.7.0"
once_cell = "1.18.0"
tempfile = "3.6.0"
thiserror = "1.0.40"
