[package]
name = "tetengo_trie"
version = "1.2.3"
authors = ["kaoru"]
edition = "2021"
description = "A trie library implemented with a double array"
readme = "README.md"
homepage = "https://www.tetengo.org/"
repository = "https://github.com/tetengo/tetengo.rs"
license = "MIT"
keywords = [
    "common-prefix-search",
    "data-structure",
    "double-array",
    "search",
    "trie",
]
categories = [
    "algorithms",
    "data-structures",
    "text-processing",
]

[dependencies]
anyhow = "1.0.89"
hashlink = "0.9.1"
memmap2 = "0.9.5"
tempfile = "3.12.0"
thiserror = "1.0.63"
