[package]
name = "tetengo_lattice"
version = "1.1.0"
authors = ["kaoru"]
edition = "2021"
description = ""
readme = "README.md"
homepage = "https://www.tetengo.org/"
repository = "https://github.com/tetengo/tetengo.rs"
license = "MIT"
keywords = [
]
categories = [
]

[dependencies]
