[build]
rustflags = [
    "-D", "warnings",
    "-D", "absolute-paths-not-starting-with-crate",
    "-D", "ambiguous-negative-literals",
    "-D", "closure-returning-async-block",
    "-D", "deprecated-in-future",
    "-D", "deprecated-safe-2024",
    "-D", "deref-into-dyn-supertrait",
    "-D", "edition-2024-expr-fragment-specifier",
    "-D", "elided-lifetimes-in-paths",
    "-D", "explicit-outlives-requirements",
    "-D", "ffi-unwind-calls",
#    "-D", "fuzzy-provenance-casts",
    "-D", "if-let-rescope",
    "-D", "impl-trait-overcaptures",
    "-D", "impl-trait-redundant-captures",
    "-D", "keyword-idents-2018",
    "-D", "keyword-idents-2024",
    "-D", "let-underscore-drop",
#    "-D", "lossy-provenance-casts",
    "-D", "macro-use-extern-crate",
    "-D", "meta-variable-misuse",
    "-D", "missing-abi",
    "-D", "missing-copy-implementations",
    "-D", "missing-debug-implementations",
    "-D", "missing-docs",
    "-D", "missing-unsafe-on-extern",
#    "-D", "multiple-supertrait-upcastable",
#    "-D", "must-not-suspend",
    "-D", "non-ascii-idents",
#    "-D", "non-exhaustive-omitted-patterns",
    "-D", "redundant-imports",
    "-D", "redundant-lifetimes",
    "-D", "rust-2021-incompatible-closure-captures",
    "-D", "rust-2021-incompatible-or-patterns",
    "-D", "rust-2021-prefixes-incompatible-syntax",
    "-D", "rust-2021-prelude-collisions",
    "-D", "rust-2024-guarded-string-incompatible-syntax",
    "-D", "rust-2024-incompatible-pat",
    "-D", "rust-2024-prelude-collisions",
    "-D", "single-use-lifetimes",
#    "-D", "supertrait-item-shadowing-definition",
#    "-D", "supertrait-item-shadowing-usage",
    "-D", "tail-expr-drop-order",
    "-D", "trivial-casts",
    "-D", "trivial-numeric-casts",
    "-D", "unit-bindings",
    "-D", "unnameable-types",
#    "-D", "unqualified-local-imports",
    "-D", "unreachable-pub",
    "-D", "unsafe-attr-outside-unsafe",
#    "-D", "unsafe-code",
    "-D", "unsafe-op-in-unsafe-fn",
    "-D", "unstable-features",
#    "-D", "unused-crate-dependencies",
    "-D", "unused-extern-crates",
    "-D", "unused-import-braces",
    "-D", "unused-lifetimes",
    "-D", "unused-macro-rules",
    "-D", "unused-qualifications",
    "-D", "unused-results",
    "-D", "variant-size-differences",
    "-D", "clippy::all",
    "-D", "clippy::cargo",
    "-D", "clippy::complexity",
    "-D", "clippy::correctness",
    "-D", "clippy::nursery",
    "-D", "clippy::pedantic",
    "-D", "clippy::perf",
#    "-D", "clippy::restriction",
    "-D", "clippy::style",
    "-D", "clippy::suspicious",
    "-A", "clippy::multiple_crate_versions",
    "-A", "clippy::too_many_arguments",
    "-A", "clippy::type_complexity",
    "-A", "clippy::bool_to_int_with_if",                # pedantic

    "-A", "clippy::items_after_statements",             # pedantic
    "-A", "clippy::iter_without_into_iter",             # pedantic
    "-A", "clippy::manual_let_else",                    # pedantic
    "-A", "clippy::match_same_arms",                    # pedantic
    "-A", "clippy::must_use_candidate",                 # pedantic
    "-A", "clippy::needless_pass_by_value",             # pedantic
    "-A", "clippy::range_plus_one",                     # pedantic
    "-A", "clippy::redundant_closure_for_method_calls", # pedantic
    "-A", "clippy::return_self_not_must_use",           # pedantic
    "-A", "clippy::should_panic_without_expect",        # pedantic
    "-A", "clippy::similar_names",                      # pedantic
    "-A", "clippy::single_match_else",                  # pedantic
    "-A", "clippy::too_many_lines",                     # pedantic
    "-A", "clippy::uninlined_format_args",              # pedantic
    "-A", "clippy::unnecessary_semicolon",              # pedantic
    "-A", "clippy::unnecessary_wraps",                  # pedantic
    "-A", "clippy::unreadable_literal",                 # pedantic

    "-A", "clippy::cognitive_complexity",           # nursery
    "-A", "clippy::missing_const_for_fn",           # nursery
    "-A", "clippy::needless_collect",               # nursery
    "-A", "clippy::option_if_let_else",             # nursery
    "-A", "clippy::redundant_clone",                # nursery
    "-A", "clippy::redundant_pub_crate",            # nursery
    "-A", "clippy::significant_drop_tightening",    # nursery
    "-A", "clippy::string_lit_as_bytes",            # nursery
    "-A", "clippy::use_self",                       # nursery
]
