[build]
rustflags = [
    "-D", "warnings",
    "-D", "absolute-paths-not-starting-with-crate",
    "-D", "ambiguous-negative-literals",
    "-D", "closure-returning-async-block",
    "-D", "deprecated-in-future",
    "-D", "deprecated-safe-2024",
    "-D", "deref-into-dyn-supertrait",
    "-D", "edition-2024-expr-fragment-specifier",
    "-D", "elided-lifetimes-in-paths",
    "-D", "explicit-outlives-requirements",
    "-D", "ffi-unwind-calls",
#    "-D", "fuzzy-provenance-casts",
    "-D", "if-let-rescope",
    "-D", "impl-trait-overcaptures",
    "-D", "impl-trait-redundant-captures",
    "-D", "keyword-idents-2018",
    "-D", "keyword-idents-2024",
    "-D", "let-underscore-drop",
#    "-D", "lossy-provenance-casts",
    "-D", "macro-use-extern-crate",
    "-D", "meta-variable-misuse",
    "-D", "missing-abi",
    "-D", "missing-copy-implementations",
    "-D", "missing-debug-implementations",
    "-D", "missing-docs",
    "-D", "missing-unsafe-on-extern",
#    "-D", "multiple-supertrait-upcastable",
#    "-D", "must-not-suspend",
    "-D", "non-ascii-idents",
#    "-D", "non-exhaustive-omitted-patterns",
    "-D", "redundant-imports",
    "-D", "redundant-lifetimes",
    "-D", "rust-2021-incompatible-closure-captures",
    "-D", "rust-2021-incompatible-or-patterns",
    "-D", "rust-2021-prefixes-incompatible-syntax",
    "-D", "rust-2021-prelude-collisions",
    "-D", "rust-2024-guarded-string-incompatible-syntax",
    "-D", "rust-2024-incompatible-pat",
    "-D", "rust-2024-prelude-collisions",
    "-D", "single-use-lifetimes",
#    "-D", "supertrait-item-shadowing-definition",
#    "-D", "supertrait-item-shadowing-usage",
    "-D", "tail-expr-drop-order",
    "-D", "trivial-casts",
    "-D", "trivial-numeric-casts",
    "-D", "unit-bindings",
    "-D", "unnameable-types",
#    "-D", "unqualified-local-imports",
    "-D", "unreachable-pub",
    "-D", "unsafe-attr-outside-unsafe",
#    "-D", "unsafe-code",
    "-D", "unsafe-op-in-unsafe-fn",
    "-D", "unstable-features",
#    "-D", "unused-crate-dependencies",
    "-D", "unused-extern-crates",
    "-D", "unused-import-braces",
    "-D", "unused-lifetimes",
    "-D", "unused-macro-rules",
    "-D", "unused-qualifications",
    "-D", "unused-results",
    "-D", "variant-size-differences",
    "-D", "clippy::all",
    "-D", "clippy::cargo",
    "-D", "clippy::complexity",
    "-D", "clippy::correctness",
#    "-D", "clippy::nursery",
#    "-D", "clippy::pedantic",
    "-D", "clippy::perf",
#    "-D", "clippy::restriction",
    "-D", "clippy::style",
#    "-D", "clippy::suspicious",
    "-A", "clippy::multiple_crate_versions",
    "-A", "clippy::too_many_arguments",
]
