[build]
rustflags = [
    "-D", "absolute_paths_not_starting_with_crate",
#    "-D", "box_pointers",
    "-D", "elided_lifetimes_in_paths",
    "-D", "explicit_outlives_requirements",
#    "-D", "ffi_unwind_calls",
#    "-D", "fuzzy_provenance_casts",
    "-D", "keyword_idents",
    "-D", "let_underscore_drop",
#    "-D", "lossy_provenance_casts",
    "-D", "macro_use_extern_crate",
    "-D", "meta_variable_misuse",
    "-D", "missing_abi",
    "-D", "missing_copy_implementations",
    "-D", "missing_debug_implementations",
    "-D", "missing_docs",
#    "-D", "must_not_suspend",
    "-D", "non_ascii_idents",
#    "-D", "non_exhaustive_omitted_patterns",
    "-D", "noop_method_call",
    "-D", "pointer_structural_match",
    "-D", "rust_2021_incompatible_closure_captures",
    "-D", "rust_2021_incompatible_or_patterns",
    "-D", "rust_2021_prefixes_incompatible_syntax",
    "-D", "rust_2021_prelude_collisions",
    "-D", "single_use_lifetimes",
    "-D", "trivial_casts",
    "-D", "trivial_numeric_casts",
    "-D", "unreachable_pub",
#    "-D", "unsafe_code",
    "-D", "unsafe_op_in_unsafe_fn",
    "-D", "unstable_features",
    "-D", "unused_crate_dependencies",
    "-D", "unused_extern_crates",
    "-D", "unused_import_braces",
    "-D", "unused_lifetimes",
    "-D", "unused_macro_rules",
    "-D", "unused_qualifications",
    "-D", "unused_results",
    "-D", "unused_tuple_struct_fields",
    "-D", "variant_size_differences",
]
