# GitHub Actions Workflow
# Build on Windows
# Copyright (C) 2023-2024 kaoru  https://www.tetengo.org/

name: Linux

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:     [ v* ]
  pull_request:
    branches: [ main ]

env:
  RUST_VER: 1.80.0

jobs:
  verify_project:
    name:    cargo verify-project
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo verify-project
      shell: bash
      run: |
        rustup update ${{ env.RUST_VER }}
        cargo verify-project --verbose
  
  format:
    name:    cargo fmt
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo fmt
      shell: bash
      run: |
        rustup update ${{ env.RUST_VER }}
        cargo fmt --check --verbose
  
  lint:
    name:    cargo clippy
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo clippy
      shell: bash
      run: |
        rustup update ${{ env.RUST_VER }}
        cargo clippy
  
  document:
    name:    cargo doc
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo doc
      shell: bash
      run: |
        rustup update ${{ env.RUST_VER }}
        cargo doc --verbose
  
  build_and_test:
    name:    cargo build & test
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo build
      shell: bash
      run: |
        rustup update ${{ env.RUST_VER }}
        cargo build --release --verbose
    
    - name: cargo test
      shell: bash
      run: |
        rustup update ${{ env.RUST_VER }}
        cargo test --release --verbose
