# GitHub Actions Workflow
# Build on Windows
# Copyright (C) 2023-2024 kaoru  https://www.tetengo.org/

name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:     [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  verify_project:
    name:    cargo verify-project
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo verify-project
      shell: cmd
      run: |
        cargo verify-project --verbose
  
  format:
    name:    cargo fmt
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo fmt
      shell: cmd
      run: |
        cargo fmt --check --verbose
  
  lint:
    name:    cargo clippy
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo clippy
      shell: cmd
      run: |
        cargo clippy --all-targets
  
  document:
    name:    cargo doc
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo doc
      shell: cmd
      run: |
        cargo doc --verbose
  
  build_and_test:
    name:    cargo build & test
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: cargo build
      shell: cmd
      run: |
        cargo build --release --all-targets --verbose
    
    - name: cargo test
      shell: cmd
      run: |
        cargo test --release --all-targets --verbose
  